In [1]:
import pandas as pd

In [15]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc'
url = f'{prefix}/taxi_zone_lookup.csv'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

In [18]:
# df = pd.read_csv(url)
# df = pd.read_csv(url, nrows=100)
dtype = {
    "LocationID": "Int64",
    "Borough": "string",
    "Zone": "string",
    "service_zone": "string"
}

df = pd.read_csv(
    url, dtype=dtype
)

In [19]:
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [20]:
df.dtypes

LocationID       Int64
Borough         string
Zone            string
service_zone    string
dtype: object

In [21]:
df.shape

(265, 4)

In [22]:
df['Zone']

0               Newark Airport
1                  Jamaica Bay
2      Allerton/Pelham Gardens
3                Alphabet City
4                Arden Heights
                ...
260         World Trade Center
261             Yorkville East
262             Yorkville West
263                         NV
264                       <NA>
Name: Zone, Length: 265, dtype: string

In [34]:
!uv add sqlalchemy psycopg2-binary

Resolved 118 packages in 1.06s
Prepared 3 packages in 169ms
░░░░░░░░░░░░░░░░░░░░ [0/3] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 3 packages in 106ms
 + greenlet==3.5.3
 + psycopg2-binary==2.9.12
 + sqlalchemy==2.0.51

In [35]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [36]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [38]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [37]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [40]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [41]:
!uv add tqdm

Resolved 119 packages in 1.32s
Prepared 1 package in 40ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 33ms
 + tqdm==4.68.4

In [42]:
from tqdm.auto import tqdm
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]